_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 3d11a2b7-a1e5-4e88-af90-3cc538741018
name: Local Ecommerce Portal
mail: utkarsh.singh@innoraft.com
slogan: ''
page:
  403: /node/18
  404: /node/17
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
